export const workplaceMock = {
    "/api/workplace/list/2": {
        success: true,
        error: 0,
        data: {
            size: 25,
            total_elements: 3,
            total_pages: 1,
            empty: false,
            first: true,
            last: true,
            number: 0,
            number_of_elements: 3,
            content: [
                {
                    id: 2,
                    title: "Staion2",
                    ip: "192.155.54.23",
                    mac: "23.32.3233234",
                    description: "top best",
                    active: true,
                },
            ],
        },
    },
    "/api/workplace/list/1": {
        success: true,
        error: 0,
        data: {
            size: 25,
            total_elements: 3,
            total_pages: 1,
            empty: false,
            first: true,
            last: true,
            number: 0,
            number_of_elements: 3,
            content: [
                {
                    id: 1,
                    title: "Staion1",
                    ip: "192.155.54.23",
                    mac: "23.32.3233234",
                    description: "top best",
                    active: true,
                },
            ],
        },
    },
    "/api/workplace/list": {
        success: true,
        error: 0,
        data: {
            size: 25,
            total_elements: 3,
            total_pages: 1,
            empty: false,
            first: true,
            last: true,
            number: 0,
            number_of_elements: 3,
            content: [
                {
                    id: 1,
                    title: "Staion1",
                    ip: "192.155.54.23",
                    mac: "23.32.3233234",
                    description: "top best",
                    active: true,
                },
                {
                    id: 2,
                    title: "Staion2",
                    ip: "192.155.54.23",
                    mac: "23.32.3233234",
                    description: "top best",
                    active: true,
                },
                {
                    id: 3,
                    title: "Staion3",
                    ip: "192.155.54.23",
                    mac: "23.32.3233234",
                    description: "top best",
                    active: true,
                },
            ],
        },
    },
};
